create sequence USERID_SEQ start with 1;
drop table USER_ACCOUNTS;
CREATE TABLE USER_ACCOUNTS
(
    USERID INT NOT NULL,
    USERNAME VARCHAR(40) NOT NULL UNIQUE,
    PASSWORD VARCHAR(40) NOT NULL,
    HUNTER_NAME VARCHAR(40) NOT NULL,
    RANK INT NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    CONSTRAINT PK_USER_ID PRIMARY KEY (USERID)
);

create sequence TRADEID_SEQ start with 1;

CREATE TABLE TRADES
(
    TRADEID INT NOT NULL,
    IS_OFFER BOOLEAN NOT NULL,
    ITEM_NAME VARCHAR(40) NOT NULL,
    ITEM_QUANTITY INT NOT NULL,
    MESSAGE VARCHAR(300) NOT NULL,
    CONSTRAINT PK_TRADE_ID PRIMARY KEY (TRADEID)
);

CREATE TABLE USER_TRADES
(
    USERID INT REFERENCES USERS(USERID),
    TRADEID INT REFERENCES TRADES(TRADEID),
    PRIMARY KEY(USERID, TRADEID)
    
);

DROP TABLE TRADES;